import type { Metadata } from "next";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { Layout } from "antd";
import { Header, Content, Footer } from "antd/lib/layout/layout";
import "./globals.css";
import HeaderMenu from "@/components/HeaderMenu";

export const metadata: Metadata = {
  title: "Packiyo Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body suppressHydrationWarning={true}>
        <AntdRegistry>
          <Layout>
            <Header className="flex items-center">
              <HeaderMenu />
            </Header>
            <Content className="px-10 my-4">
              <div className="min-h-[70vh] p-0 rounded-lg bg-white">
                {children}
              </div>
            </Content>
            <Footer className="text-center">
              Packiyo ©{new Date().getFullYear()} Created by Matheus Conti
            </Footer>
          </Layout>
        </AntdRegistry>
      </body>
    </html>
  );
}
